apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-arc-sample
  namespace: arc-k8s-demo
spec:
  releaseName: arc-k8s-demo
  chart:
    git: https://github.com/svallala/arc-sample
    ref: master
    path: charts/helm-chart-test
    version: 1.0
  values:
    name: arc-k8s-demo
